on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@v5
        with:
          cache: true
          run_install: |
            - args: [--prefer-offline, --frozen-lockfile]
      - uses: actions/cache@v5
        with:
          key: eslint-cache-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('pnpm-lock.yaml', 'eslint.config.ts') }}
          path: |
            .eslintcache
      - run: pnpm check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@v5
        with:
          cache: true
          run_install: |
            - args: [--prefer-offline, --frozen-lockfile]
      - run: pnpm build-only --mode e2e
      - uses: actions/upload-artifact@v7
        with:
          name: e2e-build
          path: dist/
          overwrite: true

  e2e:
    needs: build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [ chrome, edge, firefox ]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@v5
        with:
          cache: true
          run_install: false
      - uses: actions/download-artifact@v8
        with:
          name: e2e-build
          path: dist/
      - uses: cypress-io/github-action@v7
        env:
          TZ: Europe/Amsterdam
        with:
          package-manager-cache: false
          start: cat /etc/localtime && pnpm preview
          browser: ${{ matrix.browser }}
